# Generated by Django 6.1.1 on 2026-10-02 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("teams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Secret",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("valor_cifrado", models.TextField()),
                (
                    "entorno",
                    models.CharField(
                        choices=[
                            ("DEV", "Desarrollo"),
                            ("STG", "Staging"),
                            ("PRD", "Produccion"),
                        ],
                        default="DEV",
                        max_length=3,
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "creador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secretos_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "equipos",
                    models.ManyToManyField(
                        blank=True, related_name="secretos_creados", to="teams.team"
                    ),
                ),
            ],
        ),
    ]
